export const ROUTES = {
  HOME:          "/",
  LOGIN:         "/login",
  REGISTER:      "/register",
  DASHBOARD:     "/dashboard",
  USERS:         "/users",
  ROLES:         "/roles",
  SKILL:         "/skill",
  CAREER:        "/career",
  CV:            "/cv",
  INTERVIEW:     "/interview",
  PROFILE:       "/profile",
  PROGRESS:      "/progress",
  NOTIFICATIONS: "/notifications",
  ADMIN_LOGIN:   "/admin",
  SETUP:         "/setup",
} as const;
